export const DummyData = [
  {
    id: 1,
    firstName: "Lotti",
    lastName: "Gasquoine",
    dob: "1998-06-12",
    country: "Philippines",
    address: "1 Hayes Center",
    contactType: "phone",
    contact: "807-584-1171",
  },
  {
    id: 2,
    firstName: "Bendite",
    lastName: "Desantis",
    dob: "1956-02-08",
    country: "Indonesia",
    address: "7925 Duke Center",
    contactType: "phone",
    contact: "285-529-3193",
  },
  {
    id: 3,
    firstName: "Denice",
    lastName: "Jori",
    dob: "2003-10-13",
    country: "Russia",
    address: "530 Oak Valley Plaza",
    contactType: "email",
    contact: "jDenice@gmai.com",
  },
  {
    id: 4,
    firstName: "Darline",
    lastName: "Bavridge",
    dob: "2012-12-04",
    country: "Mauritania",
    address: "95374 Columbus Alley",
    contactType: "phone",
    contact: "537-695-2196",
  },
  {
    id: 5,
    firstName: "Marcy",
    lastName: "Martusov",
    dob: "2002-05-20",
    country: "Indonesia",
    address: "194 Ruskin Center",
    contactType: "phone",
    contact: "577-550-5299",
  },
  {
    id: 6,
    firstName: "Betsy",
    lastName: "Dayes",
    dob: "1956-05-04",
    country: "Portugal",
    address: "3 Beilfuss Drive",
    contactType: "email",
    contact: "betsika@gmail.com",
  },
  {
    id: 7,
    firstName: "Phillida",
    lastName: "Knewstubb",
    dob: "1956-12-10",
    country: "Finland",
    address: "9587 Northport Center",
    contactType: "phone",
    contact: "484-176-4435",
  },
  {
    id: 8,
    firstName: "Sherry",
    lastName: "Brightling",
    dob: "1995-02-04",
    country: "China",
    address: "69 Ohio Street",
    contactType: "phone",
    contact: "824-453-5853",
  },
  {
    id: 9,
    firstName: "Lucienne",
    lastName: "Bettam",
    dob: "1979-05-23",
    country: "Indonesia",
    address: "938 Dayton Street",
    contactType: "phone",
    contact: "555-327-0694",
  },
  {
    id: 10,
    firstName: "Linda",
    lastName: "Malacrida",
    dob: "1956-11-04",
    country: "Argentina",
    address: "261 Badeau Way",
    contactType: "email",
    contact: "malaLinda@gmail.com",
  },
];
